[package]
name = "axum-hello-world-st"
version = "0.1.0"
authors = ["Programatik <programatik29@gmail.com>"]
edition = "2018"

[dependencies]
axum = "0.2"
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1"
tokio = { version = "1", features = ["full"] }
